locale: "fr-FR"
title: Baptiste Manusset # Title of your site
url: "https://baptistemanusset.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""
# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Developpeur de jeux vidéo en Vr, je suis passionné de VR et de modélisation 3D, je crée des mondes immersifs en utilisant des outils numériques, tout en explorant des supports traditionnels pour enrichir ma créativité.
# Author details for the jekyll-seo-tag gem
author:
  name: Baptiste Manusset
  email: baptiste.manusset@gmail.com
  twitter: itsbaptiste
# Social details for the jekyll-seo-tag gem
social:
  name: ItsBaptiste
  links:
    - https://twitter.com/ItsBaptiste

permalink: pretty
# permalink: :title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-youtube
#  - jekyll-manager



# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234
# -----------
# CloudCannon
social_icons:
  - Twitter
  - Github

collections:
  blogs:
    output: true
  timelines:
    output: false
  statics:
    output: false
  posts:
      output: true
      permalink: /:title/
sass:
  sass_dir: _scss
  style: :compressed


exclude: ['__templates','*.bat','*.act','LICENCE','Gemfile','Gemfile.lock']
  


############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: false
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 100

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/images/"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################